application:
  subdomain: qmmusic
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://qmmusic:6688/
services:
  qmmusic:
    # upstream: qmmusic/qm-music:v2.5.0
    image: docker.1ms.run/qmmusic/qm-music:v2.5.0
    environment:
      - QM_FFMPEG_ENABLE=true
      - TZ=Asia/Shanghai
      - QM_SPOTIFY_ENABLE=false
      - QM_SPOTIFY_CLIENT_ID=[QM_SPOTIFY_CLIENT_ID]
      - QM_SPOTIFY_CLIENT_SECRET=[QM_SPOTIFY_CLIENT_SECRET]
      - QM_LASTFM_ENABLE=false
      - QM_LASTFM_API_KEY=[QM_LASTFM_API_KEY]
      - QM_REFRESH_AUTO=true
    binds:
      - /lzcapp/var/music:/data/qm-music/music_dir
      - /lzcapp/var/db:/data/qm-music/db
      - /lzcapp/cache/qmmusic:/data/qm-music/cache
